Repository trebol-ecommerce/ngx-trebol-frontend, pull requests merged in 2020-10, with the labels that each got.

#21 #20 add i18n translator to use in angular material modal
  src/app/i18n/i18n.constants.ts
  src/app/i18n/i18n.models.ts
  src/functions/i18n.translator.spec.ts
  src/functions/i18n.translator.ts
Labels: enhancement

#23 Add examples to local memory module
  src/app/data/local-memory/clients.local-memory-crud.service.ts
  src/app/data/local-memory/sales.local-memory-crud.service.ts
  src/app/data/local-memory/sellers.local-memory-crud.service.ts
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#25 Add shopping cart service tests
  src/app/store/store.service.spec.ts
Labels: enhancement, hacktoberfest

#32 Add unit tests for cart checking out
  debug.log
  src/app/store/dialogs/payment-redirect-prompt/store-payment-redirect-prompt-dialog.component.spec.ts
  src/app/store/dialogs/payment-redirect-prompt/store-payment-redirect-prompt-dialog.component.ts
  src/app/store/dialogs/product-details/store-product-details-dialog.component.spec.ts
  src/app/store/dialogs/product-details/store-product-details-dialog.component.ts
  src/app/store/header/store-header.component.html
  src/app/store/header/store-header.component.spec.ts
  src/app/store/header/store-header.component.ts
  src/app/store/routes/cart-review/store-cart-review.component.html
  src/app/store/routes/cart-review/store-cart-review.component.spec.ts
  src/app/store/routes/cart-review/store-cart-review.component.ts
  src/app/store/store.service.spec.ts
  src/app/store/store.service.ts
Labels: hacktoberfest

#33 Unit tests for logging in and out
  package-lock.json
  package.json
  src/app/app.service.ts
  src/app/management/management-routing.guard.ts
  src/app/shared/edit-profile-form-dialog/edit-profile-form.service.spec.ts
  src/app/store/dialogs/login-form/store-login-form-dialog.component.spec.ts
  src/app/store/dialogs/login-form/store-login-form-dialog.component.ts
  src/app/store/header/store-header.component.html
  src/app/store/header/store-header.component.spec.ts
  src/app/store/header/store-header.component.ts
  src/app/store/routes/cart-review/store-cart-review.component.spec.ts
  src/app/store/routes/cart-review/store-cart-review.component.ts
Labels: enhancement, hacktoberfest
